name: social_ease_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  intl: ^0.18.1
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.3.1
  firebase_ui_auth: ^1.9.1
  bloc_test: ^9.1.4
  provider: ^6.0.5
  uuid: ^4.1.0
  animated_bottom_navigation_bar: ^1.3.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^2.4.2
  firebase_storage_mocks: ^0.6.1
  mocktail: ^1.0.1

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lottie/
    